# --- !Ups

CREATE TABLE "user"(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(60) NOT NULL,
  password VARCHAR(60) NOT NULL,
  currency VARCHAR(20) NOT NULL,
  CONSTRAINT "unique_email" UNIQUE(email)
);

CREATE TABLE "budget"(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  userId INTEGER NOT NULL,
  creationDate DATE NOT NULL,
  name VARCHAR(60) NOT NULL,
  type VARCHAR(60) NOT NULL,
  used DOUBLE NOT NULL,
  "left" DOUBLE NOT NULL,
  exceeding DOUBLE NOT NULL,
  persistent INTEGER NOT NULL,
  reported BOOLEAN NOT NULL,
  color VARCHAR(60) NOT NULL,
  FOREIGN KEY(userId) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "takes_from"(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  budgetGoesToId INTEGER NOT NULL,
  budgetTakesFromId INTEGER NOT NULL,
  "order" INTEGER NOT NULL,
  FOREIGN KEY(budgetGoesToId) REFERENCES "budget"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(budgetTakesFromId) REFERENCES "budget"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "unique_row" UNIQUE(budgetGoesToId, budgetTakesFromId)
);

CREATE TABLE "transaction"(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  userId INTEGER NOT NULL,
  budgetId INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  date DATE NOT NULL,
  amount DOUBLE NOT NULL,
  FOREIGN KEY(userId) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(budgetId) REFERENCES "budget"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "exchange"(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  userId INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  date DATE NOT NULL,
  type VARCHAR(60) NOT NULL,
  amount DOUBLE NOT NULL,
  FOREIGN KEY(userId) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "income_outcome"(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  userId INTEGER NOT NULL,
  date DATE NOT NULL,
  income DOUBLE NOT NULL,
  outcome DOUBLE NOT NULL,
  FOREIGN KEY(userId) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

# --- !Downs

DROP TABLE "user";
DROP TABLE "budget";
DROP TABLE "takes_from";
DROP TABLE "transaction";
DROP TABLE "exchange";
DROP TABLE "income_outcome";
